{
  "comments": [
    "In integration and nightly build (I20060110)\n\nProgram did not suspend. \n\njunit.framework.AssertionFailedError: Program did not suspend.\nat org.eclipse.jdt.debug.tests.AbstractDebugTest.resume(AbstractDebugTest.java:461)\nat org.eclipse.jdt.debug.tests.AbstractDebugTest.resume(AbstractDebugTest.java:442)\nat org.eclipse.jdt.debug.tests.core.MethodBreakpointTests.testInnerClassesHit(MethodBreakpointTests.java:160)\nat org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:53)\nat java.lang.Thread.run(Thread.java:534)",
    "From N-20060118\n\nProgram did not terminate. \n\njunit.framework.AssertionFailedError: Program did not terminate.\nat org.eclipse.jdt.debug.tests.AbstractDebugTest.resumeAndExit(AbstractDebugTest.java:527)\nat org.eclipse.jdt.debug.tests.core.MethodBreakpointTests.testInnerClassesHit(MethodBreakpointTests.java:170)\nat org.eclipse.jdt.debug.tests.DebugSuite$1.run(DebugSuite.java:53)\nat java.lang.Thread.run(Thread.java:534)\n",
    "Have not seen this failure of late."
  ],
  "commentCreationDates": [
    "2006-01-11T13:49:01+01:00",
    "2006-01-18T15:19:10+01:00",
    "2006-03-08T15:23:48+01:00"
  ],
  "traces": [
    {
      "exceptionType": "junit.framework.AssertionFailedError",
      "message": "Program did not suspend.",
      "elements": [
        {
          "method": "org.eclipse.jdt.debug.tests.AbstractDebugTest.resume",
          "source": "AbstractDebugTest.java:461"
        },
        {
          "method": "org.eclipse.jdt.debug.tests.AbstractDebugTest.resume",
          "source": "AbstractDebugTest.java:442"
        },
        {
          "method": "org.eclipse.jdt.debug.tests.core.MethodBreakpointTests.testInnerClassesHit",
          "source": "MethodBreakpointTests.java:160"
        },
        {
          "method": "org.eclipse.jdt.debug.tests.DebugSuite$1.run",
          "source": "DebugSuite.java:53"
        },
        {
          "method": "java.lang.Thread.run",
          "source": "Thread.java:534"
        }
      ],
      "number": 0,
      "commentIndex": 0,
      "bugId": "123419",
      "date": "2006-01-11T13:49:01+01:00",
      "product": "JDT",
      "component": "Debug",
      "severity": "normal"
    },
    {
      "exceptionType": "junit.framework.AssertionFailedError",
      "message": "Program did not terminate.",
      "elements": [
        {
          "method": "org.eclipse.jdt.debug.tests.AbstractDebugTest.resumeAndExit",
          "source": "AbstractDebugTest.java:527"
        },
        {
          "method": "org.eclipse.jdt.debug.tests.core.MethodBreakpointTests.testInnerClassesHit",
          "source": "MethodBreakpointTests.java:170"
        },
        {
          "method": "org.eclipse.jdt.debug.tests.DebugSuite$1.run",
          "source": "DebugSuite.java:53"
        },
        {
          "method": "java.lang.Thread.run",
          "source": "Thread.java:534"
        }
      ],
      "number": 1,
      "commentIndex": 1,
      "bugId": "123419",
      "date": "2006-01-18T15:19:10+01:00",
      "product": "JDT",
      "component": "Debug",
      "severity": "normal"
    }
  ],
  "groupId": "123419",
  "bugId": "123419",
  "date": "2006-01-11T13:49:01+01:00",
  "product": "JDT",
  "component": "Debug",
  "severity": "normal"
}