{
  "comments": [
    "Build M5\n\nI tried to import a plugin from the file system.  I chose \u0027Choose plug-ins in \nthe runtime platform\u0027 and \u0027Copy plug-in contents to the workspace location\u0027.  \nWhen I clicked on next an error dialog appeared.\n\nIt said \u0027276\u0027.\n\nOnce I dismissed the error dialog, a selection list appeared.  The list had \nmany unchecked checkboxes, and none of them had any text next to them.\n\nThe following trace was in the .log file:\n\n\n\u003c/log-entry\u003e\n\u003clog-entry date\u003d\"Fri Apr 19 17:51:31 EDT 2002\"\u003e\n  \u003cstatus\n     plugin-id\u003d\"org.eclipse.pde.ui\"\n     severity\u003d\"ERROR\"\n     message\u003d\"276\"\n     code\u003d\"0\"\u003e\n    \u003cexception\n       message\u003d\"276\"\n       trace\u003d\"\njava.lang.ArrayIndexOutOfBoundsException: 276\n\tat java.util.Vector.elementAt(Vector.java(Compiled Code))\n\tat org.eclipse.pde.internal.core.ExternalModelManager.getFragment\n(ExternalModelManager.java:140)\n\tat \norg.eclipse.pde.internal.ui.wizards.imports.PluginImportWizardDetailedPage$1.ru\nn(PluginImportWizardDetailedPage.java:203)\n\tat org.eclipse.jface.operation.ModalContext$ModalContextThread.run\n(ModalContext.java:98)\n\"\u003e\n    \u003c/exception\u003e\n  \u003c/status\u003e\n\u003c/log-entry\u003e",
    "Created an attachment (id\u003d671)\nSnapshot of error dialog\n",
    "More info - it turns out that if I scroll down the list I eventually do \nencounter some names.  Only the top 63 elements are empty.  If I check any of \nthe \u0027empty\u0027 plugins, the counter (0 out of 338 selected) does not change.  If \nI click on a named element it does change.\n\nIt\u0027s also curious that I only seem to have 53 folders in my plugin folder (why \n338?)\n\nI think that the problem is probably related to the Preferences-\u003ePlug-in \nDevelopment-\u003eTarget Platform-\u003eLocate non-workspace plug-ins... option.  I had \nthis option set to point at an installation of WSADIE.  When I changed it back \nto \u0027This application\u0027, I was able to use the PDE import again.\n\n",
    "The problem was related to existence of fragments in the build. I released the \nfix into HEAD today. It will appear in the next integration build (Tuesday)."
  ],
  "commentCreationDates": [
    "2002-04-19T23:45:43+02:00",
    "2002-04-19T23:46:06+02:00",
    "2002-04-20T00:10:42+02:00",
    "2002-04-25T23:43:02+02:00"
  ],
  "traces": [
    {
      "exceptionType": "java.lang.ArrayIndexOutOfBoundsException",
      "message": "276",
      "elements": [
        {
          "method": "java.util.Vector.elementAt",
          "source": "Vector.java(Compiled Code)"
        },
        {
          "method": "org.eclipse.pde.internal.core.ExternalModelManager.getFragment",
          "source": "ExternalModelManager.java:140"
        },
        {
          "method": "org.eclipse.pde.internal.ui.wizards.imports.PluginImportWizardDetailedPage$1.run",
          "source": "PluginImportWizardDetailedPage.java:203"
        },
        {
          "method": "org.eclipse.jface.operation.ModalContext$ModalContextThread.run",
          "source": "ModalContext.java:98"
        }
      ],
      "number": 0,
      "commentIndex": 0,
      "bugId": "14270",
      "date": "2002-04-19T23:45:43+02:00",
      "product": "PDE",
      "component": "UI",
      "severity": "normal"
    }
  ],
  "groupId": "14270",
  "bugId": "14270",
  "date": "2002-04-19T23:45:43+02:00",
  "product": "PDE",
  "component": "UI",
  "severity": "normal"
}