{
  "comments": [
    "I20060704-0800, WinXP\n- I installed the above I-build and started up a workspace that I\u0027ve used for some time. \n- I received the CVS password prompt\n- Typed in my password, it was rejected.  Thinking I might have recently changed it or typed it wrong, I tried many other combinations\n- I went to committer tools to see if the password I believed to be correct was.  It was correct.\n- Just to be paranoid, I changed my password from the committer tools.\n- I started up a 3.2 build and workspace and typed in my newly changed password.  It worked.\n- My I20060704-0800 workbench had been open all this time.  I tried to synchronize again and typed in the newly changed password.  Still rejected.\n- Finally I quit out of I20060704 and restarted.  This time it accepted the password.\n\nI carefully typed my password many times during this process so I do not believe it was a typo or mistaken password.",
    "To clarify the steps mentioned above.\nI was trying to synchronize my wrokspace to the dev.eclipse.org CVS server when I received the password prompts.  (ie, I did not randomly get the prompts).\n\nI was able to synchronize in the 3.2 build and on subsequent uses of I20060704, but was never able to get my password accepted when trying to synchronize on my first use of I20060704.",
    "We haven\u0027t been able to reproduce this and others have not reported similar problems. I moving this to the REMIND bucket for the time being. If you see the problem again, feel free to reopen. We\u0027ll reopen it if we see other similar reports.",
    "Our usual practice is to move bugs to the RESOLVED REMIND state when there is not enough information provided to address the reported issue and more information has been requested. This bug has been in the RESOLVED REMIND state for quite some time so it is being CLOSED. If you can provide the requested information or you otherwise feel that this is still an issue, please reopen the bug. If you are unable to open it due to a lack or permissions, please add a comment to the bug stating that you would like to have the request reconsidered.  I applogize for this blanket approach to bug screening but there are just to many bugs in the REMIND state for us to effectively triage them. Your help in this matter is appreciated.",
    "This just happened again.  I\u0027m wondering if it has to do with a rather stale workspace?  I have been on leave, so my workspace has been unused for 10-12 weeks.  I\u0027ve just downloaded 3.3 M5 and tried to synchronize my workspace with CVS.  \n\nJust as described in comment #0, I checked and changed my password in the CVS committer tools to make sure it wasn\u0027t a forgotten password problem.  I cannot connect.  I receive an error dialog saying there is a connection error, and this appears in my log:\n\n!SUBENTRY 1 org.eclipse.team.cvs.core 4 -6 2007-02-12 08:46:16.835\n!MESSAGE Could not connect to :extssh:sfranklin@dev.eclipse.org:/cvsroot/eclipse: CVS communication error: org.eclipse.team.internal.ccvs.ssh2.CVSSSH2ServerConnection$SSH2IOException: Connection refused: connect\n!STACK 0\norg.eclipse.team.internal.ccvs.ssh2.CVSSSH2ServerConnection$SSH2IOException: Connection refused: connect\n\tat org.eclipse.team.internal.ccvs.ssh2.CVSSSH2ServerConnection.internalOpen(CVSSSH2ServerConnection.java:193)\n\tat org.eclipse.team.internal.ccvs.ssh2.CVSSSH2ServerConnection.open(CVSSSH2ServerConnection.java:107)\n\tat org.eclipse.team.internal.ccvs.core.connection.Connection.open(Connection.java:131)\n\tat org.eclipse.team.internal.ccvs.core.connection.CVSRepositoryLocation.createConnection(CVSRepositoryLocation.java:539)\n\tat org.eclipse.team.internal.ccvs.core.connection.CVSRepositoryLocation.openConnection(CVSRepositoryLocation.java:780)\n\tat org.eclipse.team.internal.ccvs.core.client.Session.open(Session.java:159)\n\tat org.eclipse.team.internal.ccvs.core.resources.RemoteFolderMemberFetcher.performUpdate(RemoteFolderMemberFetcher.java:97)\n\tat org.eclipse.team.internal.ccvs.ui.operations.FetchMembersOperation$InternalRemoteFolderMemberFetcher.performUpdate(FetchMembersOperation.java:69)\n\tat org.eclipse.team.internal.ccvs.core.resources.RemoteFolderMemberFetcher.fetchMembers(RemoteFolderMemberFetcher.java:64)\n\tat org.eclipse.team.internal.ccvs.core.resources.RemoteFolderMemberFetcher.fetchMembers(RemoteFolderMemberFetcher.java:55)\n\tat org.eclipse.team.internal.ccvs.ui.operations.FetchMembersOperation.execute(FetchMembersOperation.java:107)\n\tat org.eclipse.team.internal.ccvs.ui.operations.CVSOperation.run(CVSOperation.java:81)\n\tat org.eclipse.team.internal.ccvs.ui.model.CVSTagElement.fetchDeferredChildren(CVSTagElement.java:136)\n\tat org.eclipse.ui.progress.DeferredTreeContentManager$1.run(DeferredTreeContentManager.java:196)\n\tat org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)\nCaused by: com.jcraft.jsch.JSchException: Session.connect: java.net.ConnectException: Connection refused: connect\n\tat com.jcraft.jsch.Session.connect(Unknown Source)\n\tat com.jcraft.jsch.Session.connect(Unknown Source)\n\tat org.eclipse.team.internal.ccvs.ssh2.JSchSession.createSession(JSchSession.java:495)\n\tat org.eclipse.team.internal.ccvs.ssh2.JSchSession.getSession(JSchSession.java:447)\n\tat org.eclipse.team.internal.ccvs.ssh2.CVSSSH2ServerConnection.internalOpen(CVSSSH2ServerConnection.java:122)\n\t... 14 more\n",
    "changed name of bug to indicate it is a current problem.\n\nThis is pretty major...I can\u0027t connect in M5.\nI tried in 3.2, it works.\nI tried in 3.3 M2, it works.\n\nI threw away my old workspace and started a new workspace in M5.  I still cannot connect in M5.  I\u0027ve carefully checked that the location settings, password, etc. are correct (they work in the other two workspaces).",
    "The launcher changed in M5 which can put your firewall into a state where it thinks it is a new program but doesn\u0027t prompt you. Try turning off your firewall and see if that helps.",
    "That did the trick. \nI was hoping once connected, I could enable my firewall again, but no luck.\nSo is there a fix in the works?\n\nAnd a bug number I should be watching instead of this one?",
    "Technically, the bug is in your firewall software so we don\u0027t have a bug in Eclipse for it (i.e. for me, my firewall just prompts me to Allow connections when I reinstall a new Eclipse). What you need to do is go into your firewall software and add Eclipse to the list of applications that are trusted."
  ],
  "commentCreationDates": [
    "2006-07-05T22:12:49+02:00",
    "2006-07-05T22:14:54+02:00",
    "2006-07-14T17:06:38+02:00",
    "2006-10-20T12:20:12+02:00",
    "2007-02-12T16:50:56+01:00",
    "2007-02-12T17:28:33+01:00",
    "2007-02-12T18:04:37+01:00",
    "2007-02-12T18:44:21+01:00",
    "2007-02-12T19:15:45+01:00"
  ],
  "traces": [
    {
      "exceptionType": "org.eclipse.team.internal.ccvs.ssh2.CVSSSH2ServerConnection$SSH2IOException",
      "message": "Connection refused: connect",
      "elements": [
        {
          "method": "org.eclipse.team.internal.ccvs.ssh2.CVSSSH2ServerConnection.internalOpen",
          "source": "CVSSSH2ServerConnection.java:193"
        },
        {
          "method": "org.eclipse.team.internal.ccvs.ssh2.CVSSSH2ServerConnection.open",
          "source": "CVSSSH2ServerConnection.java:107"
        },
        {
          "method": "org.eclipse.team.internal.ccvs.core.connection.Connection.open",
          "source": "Connection.java:131"
        },
        {
          "method": "org.eclipse.team.internal.ccvs.core.connection.CVSRepositoryLocation.createConnection",
          "source": "CVSRepositoryLocation.java:539"
        },
        {
          "method": "org.eclipse.team.internal.ccvs.core.connection.CVSRepositoryLocation.openConnection",
          "source": "CVSRepositoryLocation.java:780"
        },
        {
          "method": "org.eclipse.team.internal.ccvs.core.client.Session.open",
          "source": "Session.java:159"
        },
        {
          "method": "org.eclipse.team.internal.ccvs.core.resources.RemoteFolderMemberFetcher.performUpdate",
          "source": "RemoteFolderMemberFetcher.java:97"
        },
        {
          "method": "org.eclipse.team.internal.ccvs.ui.operations.FetchMembersOperation$InternalRemoteFolderMemberFetcher.performUpdate",
          "source": "FetchMembersOperation.java:69"
        },
        {
          "method": "org.eclipse.team.internal.ccvs.core.resources.RemoteFolderMemberFetcher.fetchMembers",
          "source": "RemoteFolderMemberFetcher.java:64"
        },
        {
          "method": "org.eclipse.team.internal.ccvs.core.resources.RemoteFolderMemberFetcher.fetchMembers",
          "source": "RemoteFolderMemberFetcher.java:55"
        },
        {
          "method": "org.eclipse.team.internal.ccvs.ui.operations.FetchMembersOperation.execute",
          "source": "FetchMembersOperation.java:107"
        },
        {
          "method": "org.eclipse.team.internal.ccvs.ui.operations.CVSOperation.run",
          "source": "CVSOperation.java:81"
        },
        {
          "method": "org.eclipse.team.internal.ccvs.ui.model.CVSTagElement.fetchDeferredChildren",
          "source": "CVSTagElement.java:136"
        },
        {
          "method": "org.eclipse.ui.progress.DeferredTreeContentManager$1.run",
          "source": "DeferredTreeContentManager.java:196"
        },
        {
          "method": "org.eclipse.core.internal.jobs.Worker.run",
          "source": "Worker.java:58"
        }
      ],
      "causedBy": {
        "exceptionType": "java.net.ConnectException",
        "message": "Connection refused: connect",
        "elements": [
          {
            "method": "com.jcraft.jsch.Session.connect",
            "source": "Unknown Source"
          },
          {
            "method": "com.jcraft.jsch.Session.connect",
            "source": "Unknown Source"
          },
          {
            "method": "org.eclipse.team.internal.ccvs.ssh2.JSchSession.createSession",
            "source": "JSchSession.java:495"
          },
          {
            "method": "org.eclipse.team.internal.ccvs.ssh2.JSchSession.getSession",
            "source": "JSchSession.java:447"
          },
          {
            "method": "org.eclipse.team.internal.ccvs.ssh2.CVSSSH2ServerConnection.internalOpen",
            "source": "CVSSSH2ServerConnection.java:122"
          }
        ],
        "number": 0,
        "commentIndex": 0
      },
      "number": 0,
      "commentIndex": 4,
      "bugId": "149731",
      "date": "2007-02-12T16:50:56+01:00",
      "product": "Platform",
      "component": "CVS",
      "severity": "major"
    }
  ],
  "groupId": "149731",
  "bugId": "149731",
  "date": "2006-07-05T22:12:49+02:00",
  "product": "Platform",
  "component": "CVS",
  "severity": "major"
}