{
  "comments": [
    "3.2 RC5\n\nVM: IBM JRE 1.5 SR3 candidate\nJava(TM) 2 Runtime Environment, Standard Edition (build jclwi32dev-20060710)\nIBM J9 VM (build 2.3, J2RE 1.5.0 IBM J9 2.3 Windows XP x86-32  (JIT enabled)\nJ9VM - 20060711_07139_lHdSMR\nJIT  - 20060710_1811_r8\nGC   - 20060707_AA)\nJCL  - 20060710\n\n- set a conditional breakpoints that checked isDisposed() on a widget\n- instead of stopping, it generated:\n\n!ENTRY org.eclipse.jdt.debug 4 120 2006-07-19 16:11:01.046\n!MESSAGE Exception processing async thread queue\n!SUBENTRY 1 org.eclipse.jdt.debug 4 120 2006-07-19 16:11:01.046\n!MESSAGE Exception processing async thread queue\n!STACK 0\njava.lang.ClassCastException: org.eclipse.jdt.internal.debug.core.model.JDINullValue incompatible with org.eclipse.jdt.internal.debug.core.model.JDIObjectValue\n\tat org.eclipse.jdt.internal.debug.core.model.JDIObjectValue.getEnclosingObject(JDIObjectValue.java:274)\n\tat org.eclipse.jdt.internal.debug.eval.ast.instructions.PushThis.execute(PushThis.java:41)\n\tat org.eclipse.jdt.internal.debug.eval.ast.engine.Interpreter.execute(Interpreter.java:50)\n\tat org.eclipse.jdt.internal.debug.eval.ast.engine.ASTEvaluationEngine$1$EvaluationRunnable.run(ASTEvaluationEngine.java:455)\n\tat org.eclipse.jdt.internal.debug.core.model.JDIThread.runEvaluation(JDIThread.java:584)\n\tat org.eclipse.jdt.internal.debug.eval.ast.engine.ASTEvaluationEngine$EvalRunnable.run(ASTEvaluationEngine.java:489)\n\tat org.eclipse.jdt.internal.debug.core.model.JDIThread$ThreadJob.run(JDIThread.java:2467)\n\tat org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)",
    "The breakpoint was in org.eclipse.ui.internal.forms.widgets.BusyIndicator on line 218.  Also had a similar one on line 221.  Not sure which one was causing the problem.  Possibly both.\n\nThe code snippet is:\n\n218: Display.getDefault().syncExec(new Runnable() {\n219:   public void run() {\n220:     animationImage \u003d null;\n221:     redraw();\n222:   }\n223: });\n",
    "this bug is fixed in 3.3 by bug 158280"
  ],
  "commentCreationDates": [
    "2006-07-19T22:21:13+02:00",
    "2006-07-19T22:24:39+02:00",
    "2007-01-26T17:25:04+01:00"
  ],
  "traces": [
    {
      "exceptionType": "java.lang.ClassCastException",
      "message": "org.eclipse.jdt.internal.debug.core.model.JDINullValue incompatible with org.eclipse.jdt.internal.debug.core.model.JDIObjectValue",
      "elements": [
        {
          "method": "org.eclipse.jdt.internal.debug.core.model.JDIObjectValue.getEnclosingObject",
          "source": "JDIObjectValue.java:274"
        },
        {
          "method": "org.eclipse.jdt.internal.debug.eval.ast.instructions.PushThis.execute",
          "source": "PushThis.java:41"
        },
        {
          "method": "org.eclipse.jdt.internal.debug.eval.ast.engine.Interpreter.execute",
          "source": "Interpreter.java:50"
        },
        {
          "method": "org.eclipse.jdt.internal.debug.eval.ast.engine.ASTEvaluationEngine$1$EvaluationRunnable.run",
          "source": "ASTEvaluationEngine.java:455"
        },
        {
          "method": "org.eclipse.jdt.internal.debug.core.model.JDIThread.runEvaluation",
          "source": "JDIThread.java:584"
        },
        {
          "method": "org.eclipse.jdt.internal.debug.eval.ast.engine.ASTEvaluationEngine$EvalRunnable.run",
          "source": "ASTEvaluationEngine.java:489"
        },
        {
          "method": "org.eclipse.jdt.internal.debug.core.model.JDIThread$ThreadJob.run",
          "source": "JDIThread.java:2467"
        },
        {
          "method": "org.eclipse.core.internal.jobs.Worker.run",
          "source": "Worker.java:58"
        }
      ],
      "number": 0,
      "commentIndex": 0,
      "bugId": "151131",
      "date": "2006-07-19T22:21:13+02:00",
      "product": "JDT",
      "component": "Debug",
      "severity": "normal"
    }
  ],
  "groupId": "151131",
  "bugId": "151131",
  "date": "2006-07-19T22:21:13+02:00",
  "product": "JDT",
  "component": "Debug",
  "severity": "normal"
}