{
  "comments": [
    "I tried profiling with default settings and also with just execution time analysis \u0026 Collect method CPU time information. I need to stop everything and reload the trace file from disk to finally getting Eclipse showing at least some statistics. But from all the profiling views just a few shoe data and e.g. Coverage statistics show numbers in column \"Methods missed\" but always \"0\" in columns \"Calls\" and \"Methods hit\" - which is of course impossible.",
    "Would it be possible to attach the application you are profiling? or workspace that you are using with the problem?\n\n",
    "*** Bug 152349 has been marked as a duplicate of this bug. ***",
    "Hi. Do you still see problem with the latest TPTP driver?",
    "Yesterday I updated my Eclipse through the Eclipse update menu wizard. Now, when I try to profile a project I just get an error:\n\n\n--------------------------------\n!ENTRY org.eclipse.hyades.trace.ui 4 0 2006-10-13 09:54:36.183\n!MESSAGE An error occurred while attempting to resolve the data collectors selected\n!STACK 1\norg.eclipse.core.runtime.CoreException: An error occurred while attempting to resolve the data collectors selected\n\tat org.eclipse.tptp.trace.ui.internal.launcher.core.LauncherUtility.createCoreException(LauncherUtility.java:120)\n\tat org.eclipse.tptp.trace.ui.internal.launcher.core.LauncherUtility.createCoreException(LauncherUtility.java:128)\n\tat org.eclipse.tptp.trace.ui.provisional.launcher.PrimaryLaunchDelegate.run(PrimaryLaunchDelegate.java:152)\n\tat java.lang.Thread.run(Thread.java:595)\n!SUBENTRY 1 org.eclipse.hyades.trace.ui 4 0 2006-10-13 09:54:36.183\n!MESSAGE An error occurred while attempting to resolve the data collectors selected\n----------------------------------------\n",
    "mass update:\nretarget from 4.3 to 4.4. Cannot be contained in 4.3 due to resource limtation.",
    "I install Eclipse 3.2 and run Callisto Update sites for TPTP and its dependencies, then run a simple profile with execution time analysis \u0026 cpu time collection. I cannot reproduce the problem reported anymore."
  ],
  "commentCreationDates": [
    "2006-07-31T18:12:47+02:00",
    "2006-07-31T18:25:49+02:00",
    "2006-07-31T19:11:24+02:00",
    "2006-10-13T01:04:53+02:00",
    "2006-10-13T09:52:10+02:00",
    "2006-10-19T23:50:48+02:00",
    "2007-01-16T04:35:35+01:00"
  ],
  "traces": [
    {
      "exceptionType": "org.eclipse.core.runtime.CoreException",
      "message": "An error occurred while attempting to resolve the data collectors selected",
      "elements": [
        {
          "method": "org.eclipse.tptp.trace.ui.internal.launcher.core.LauncherUtility.createCoreException",
          "source": "LauncherUtility.java:120"
        },
        {
          "method": "org.eclipse.tptp.trace.ui.internal.launcher.core.LauncherUtility.createCoreException",
          "source": "LauncherUtility.java:128"
        },
        {
          "method": "org.eclipse.tptp.trace.ui.provisional.launcher.PrimaryLaunchDelegate.run",
          "source": "PrimaryLaunchDelegate.java:152"
        },
        {
          "method": "java.lang.Thread.run",
          "source": "Thread.java:595"
        }
      ],
      "number": 0,
      "commentIndex": 4,
      "bugId": "152347",
      "date": "2006-10-13T09:52:10+02:00",
      "product": "TPTP Profiling",
      "component": "Platform.UI.ProfilingPerspective",
      "severity": "normal"
    }
  ],
  "groupId": "152347",
  "bugId": "152347",
  "date": "2006-07-31T18:12:47+02:00",
  "product": "TPTP Profiling",
  "component": "Platform.UI.ProfilingPerspective",
  "severity": "normal"
}