{
  "comments": [
    "Build: I20061031-0656\n\n1) Create a simple project\n2) In the file system, add file \"a.txt\" to the project\n3) Back in Eclipse, do File \u003e New \u003e File, select the project and enter a name of \"a.txt\". An internal error occurs because it is trying to open an error dialog from a modal context thread:\n\norg.eclipse.swt.SWTException: Invalid thread access\n\tat org.eclipse.swt.SWT.error(SWT.java:3407)\n\tat org.eclipse.swt.SWT.error(SWT.java:3330)\n\tat org.eclipse.swt.SWT.error(SWT.java:3301)\n\tat org.eclipse.swt.widgets.Widget.error(Widget.java:432)\n\tat org.eclipse.swt.widgets.Shell.\u003cinit\u003e(Shell.java:271)\n\tat org.eclipse.swt.widgets.Shell.\u003cinit\u003e(Shell.java:357)\n\tat org.eclipse.jface.window.Window.createShell(Window.java:482)\n\tat org.eclipse.jface.window.Window.create(Window.java:425)\n\tat org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1111)\n\tat org.eclipse.jface.window.Window.open(Window.java:785)\n\tat org.eclipse.jface.dialogs.ErrorDialog.open(ErrorDialog.java:296)\n\tat org.eclipse.jface.dialogs.ErrorDialog.openError(ErrorDialog.java:360)\n\tat org.eclipse.jface.dialogs.ErrorDialog.openError(ErrorDialog.java:325)\n\tat org.eclipse.ui.dialogs.WizardNewFileCreationPage$4.run(WizardNewFileCreationPage.java:343)\n\tat org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:113)",
    "Same for new folder wizard...\n\n\tat org.eclipse.jface.dialogs.ErrorDialog.openError(ErrorDialog.java:325)\n\tat org.eclipse.ui.dialogs.WizardNewFolderMainPage$4.run(WizardNewFolderMainPage.java:335)\n\tat org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:113)",
    "moving to platform UI.\nThis should probably go to IDE in the future, once stabilized, but for right now, I\u0027ll work on these as platform UI bugs... (easier for me to manage).\n\nInvestigate for 3.3",
    "I meant..investigate for 3.3M3...should be just a matter of a sync or async.",
    "McQ - I\u0027d like to fix this one for M3.  The fix is low risk.  The problem is caused by the fact that the new file and new folder wizards were modified to catch ExecutionExceptions thrown by the undo code, unwrap the associated CoreException, and put up a specific error dialog.  These handlers were inside the runnable with progress that is forked, hence the thread problem.\n\nPreviously, all handlers were handled outside the runnable in an InvocationTargetException, so there was no need to syncExec.\n\nBottom line - the new handlers inside the runnable need to call syncExec when putting up the error dialog.\n\nI verified that the changes work and cause the proper, specific CoreException to be shown when the operation fails due to already existent file or folder.\n\nOK to put in?",
    "Yes.\n",
    "Fixed in HEAD \u003e20061031, not sure yet which rebuild this will make it into...will update bug when it\u0027s submitted.",
    "forgot to mark fixed...",
    "should be verifiable in I20061101-0010",
    "verified on I20061101-0800, WinXP.\nIn both the new file and new folder case, the wizard properly reports the error that the resource already exists on disk."
  ],
  "commentCreationDates": [
    "2006-10-31T15:37:15+01:00",
    "2006-10-31T15:59:43+01:00",
    "2006-10-31T17:31:26+01:00",
    "2006-10-31T17:32:26+01:00",
    "2006-10-31T20:01:04+01:00",
    "2006-10-31T20:22:03+01:00",
    "2006-10-31T20:31:39+01:00",
    "2006-10-31T20:36:30+01:00",
    "2006-10-31T22:45:03+01:00",
    "2006-11-01T17:19:57+01:00"
  ],
  "traces": [
    {
      "exceptionType": "org.eclipse.swt.SWTException",
      "message": "Invalid thread access",
      "elements": [
        {
          "method": "org.eclipse.swt.SWT.error",
          "source": "SWT.java:3407"
        },
        {
          "method": "org.eclipse.swt.SWT.error",
          "source": "SWT.java:3330"
        },
        {
          "method": "org.eclipse.swt.SWT.error",
          "source": "SWT.java:3301"
        },
        {
          "method": "org.eclipse.swt.widgets.Widget.error",
          "source": "Widget.java:432"
        },
        {
          "method": "org.eclipse.swt.widgets.Shell.\u003cinit\u003e",
          "source": "Shell.java:271"
        },
        {
          "method": "org.eclipse.swt.widgets.Shell.\u003cinit\u003e",
          "source": "Shell.java:357"
        },
        {
          "method": "org.eclipse.jface.window.Window.createShell",
          "source": "Window.java:482"
        },
        {
          "method": "org.eclipse.jface.window.Window.create",
          "source": "Window.java:425"
        },
        {
          "method": "org.eclipse.jface.dialogs.Dialog.create",
          "source": "Dialog.java:1111"
        },
        {
          "method": "org.eclipse.jface.window.Window.open",
          "source": "Window.java:785"
        },
        {
          "method": "org.eclipse.jface.dialogs.ErrorDialog.open",
          "source": "ErrorDialog.java:296"
        },
        {
          "method": "org.eclipse.jface.dialogs.ErrorDialog.openError",
          "source": "ErrorDialog.java:360"
        },
        {
          "method": "org.eclipse.jface.dialogs.ErrorDialog.openError",
          "source": "ErrorDialog.java:325"
        },
        {
          "method": "org.eclipse.ui.dialogs.WizardNewFileCreationPage$4.run",
          "source": "WizardNewFileCreationPage.java:343"
        },
        {
          "method": "org.eclipse.jface.operation.ModalContext$ModalContextThread.run",
          "source": "ModalContext.java:113"
        }
      ],
      "number": 0,
      "commentIndex": 0,
      "bugId": "162916",
      "date": "2006-10-31T15:37:15+01:00",
      "product": "Platform",
      "component": "UI",
      "severity": "normal"
    }
  ],
  "groupId": "162916",
  "bugId": "162916",
  "date": "2006-10-31T15:37:15+01:00",
  "product": "Platform",
  "component": "UI",
  "severity": "normal"
}