{
  "comments": [
    "When starting g-Eclipse with a default VO that has an invalid info system endpoint the info view/system throws continuously exceptions but seems to have no problems with showing the information. Is the exception really necessary? The exceptions is te following:\n\njavax.naming.NamingException: Cannot parse url: http://www.fzk.de [Root exception is java.net.MalformedURLException: Not an LDAP URL: http://www.fzk.de]\n\tat com.sun.jndi.ldap.LdapURL.\u003cinit\u003e(Unknown Source)\n\tat com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(Unknown Source)\n\tat com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(Unknown Source)\n\tat com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(Unknown Source)\n\tat com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(Unknown Source)\n\tat javax.naming.spi.NamingManager.getInitialContext(Unknown Source)\n\tat javax.naming.InitialContext.getDefaultInitCtx(Unknown Source)\n\tat javax.naming.InitialContext.init(Unknown Source)\n\tat javax.naming.InitialContext.\u003cinit\u003e(Unknown Source)\n\tat javax.naming.directory.InitialDirContext.\u003cinit\u003e(Unknown Source)\n\tat eu.geclipse.glite.info.bdii.BDIIStore.fetchClass(BDIIStore.java:109)\n\tat eu.geclipse.glite.info.bdii.BDIIStore.fetch(BDIIStore.java:91)\n\tat eu.geclipse.glite.info.bdii.BDIIStore$1.run(BDIIStore.java:51)\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)\n\tat java.util.concurrent.FutureTask$Sync.innerRunAndReset(Unknown Source)\n\tat java.util.concurrent.FutureTask.runAndReset(Unknown Source)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(Unknown Source)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(Unknown Source)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\n\tat java.lang.Thread.run(Unknown Source)\nCaused by: java.net.MalformedURLException: Not an LDAP URL: http://www.fzk.de\n\t... 22 more",
    "George can you have a look to this. ",
    "moving to 0.5.0 M3",
    "User no longer gets this error"
  ],
  "commentCreationDates": [
    "2007-02-26T09:57:23+01:00",
    "2007-02-26T10:02:50+01:00",
    "2007-04-02T16:04:38+02:00",
    "2007-05-02T11:26:39+02:00"
  ],
  "traces": [
    {
      "exceptionType": "java.net.MalformedURLException",
      "message": "Not an LDAP URL: http://www.fzk.de]",
      "elements": [
        {
          "method": "com.sun.jndi.ldap.LdapURL.\u003cinit\u003e",
          "source": "Unknown Source"
        },
        {
          "method": "com.sun.jndi.ldap.LdapCtxFactory.getUsingURL",
          "source": "Unknown Source"
        },
        {
          "method": "com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs",
          "source": "Unknown Source"
        },
        {
          "method": "com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance",
          "source": "Unknown Source"
        },
        {
          "method": "com.sun.jndi.ldap.LdapCtxFactory.getInitialContext",
          "source": "Unknown Source"
        },
        {
          "method": "javax.naming.spi.NamingManager.getInitialContext",
          "source": "Unknown Source"
        },
        {
          "method": "javax.naming.InitialContext.getDefaultInitCtx",
          "source": "Unknown Source"
        },
        {
          "method": "javax.naming.InitialContext.init",
          "source": "Unknown Source"
        },
        {
          "method": "javax.naming.InitialContext.\u003cinit\u003e",
          "source": "Unknown Source"
        },
        {
          "method": "javax.naming.directory.InitialDirContext.\u003cinit\u003e",
          "source": "Unknown Source"
        },
        {
          "method": "eu.geclipse.glite.info.bdii.BDIIStore.fetchClass",
          "source": "BDIIStore.java:109"
        },
        {
          "method": "eu.geclipse.glite.info.bdii.BDIIStore.fetch",
          "source": "BDIIStore.java:91"
        },
        {
          "method": "eu.geclipse.glite.info.bdii.BDIIStore$1.run",
          "source": "BDIIStore.java:51"
        },
        {
          "method": "java.util.concurrent.Executors$RunnableAdapter.call",
          "source": "Unknown Source"
        },
        {
          "method": "java.util.concurrent.FutureTask$Sync.innerRunAndReset",
          "source": "Unknown Source"
        },
        {
          "method": "java.util.concurrent.FutureTask.runAndReset",
          "source": "Unknown Source"
        },
        {
          "method": "java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101",
          "source": "Unknown Source"
        },
        {
          "method": "java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic",
          "source": "Unknown Source"
        },
        {
          "method": "java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run",
          "source": "Unknown Source"
        },
        {
          "method": "java.util.concurrent.ThreadPoolExecutor$Worker.runTask",
          "source": "Unknown Source"
        },
        {
          "method": "java.util.concurrent.ThreadPoolExecutor$Worker.run",
          "source": "Unknown Source"
        },
        {
          "method": "java.lang.Thread.run",
          "source": "Unknown Source"
        }
      ],
      "number": 0,
      "commentIndex": 0,
      "bugId": "175501",
      "date": "2007-02-26T09:57:23+01:00",
      "product": "gEclipse",
      "component": "middleware",
      "severity": "normal"
    }
  ],
  "groupId": "175501",
  "bugId": "175501",
  "date": "2007-02-26T09:57:23+01:00",
  "product": "gEclipse",
  "component": "middleware",
  "severity": "normal"
}