{
  "comments": [
    "Build ID: I20070503-1400\n\nSteps To Reproduce:\n1. Create and launch a MySQL agent from the launch config\n2. Once the agent appears in the Profile Monitor, press \u0027Start Monitoring\u0027.\n3. Observe that the agent terminates itself.\n\n\nMore information:\nThis may be a problem with the AC, since the agent itself hasn\u0027t changed since the last successfully tested TPTP build.\n\nFor JDBC connectivity, I was using mysql-connector-java-5.0.6-bin.jar",
    "Need to resolve this in i4.",
    "Client System (Eclipse and AC)\n\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\nHostname - badger\nHW - IBM Thinkpad T41\nOS - Microsoft Windows XP Professional, 2002 Edition, SP2\nJVM - jre1.5.0_09\n\nRemote System (MySQL-5.0.21)\n\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\nHostname - shredder\nHW - IBM eServer xSeries 306 (8489-4Ty)\nOS - Ubuntu Linux 5.1.0",
    "Created an attachment (id\u003d68173)\nAgent Controller log with DEBUG on\n\nThis log file covers the following activities...\n\n1. Start the AC\n2. Try to launch a MySQL agent\n3. Stop the AC",
    "Created an attachment (id\u003d68641)\nAnother AC log using the TPTP 4.4 driver (TPTP-4.4.0-200705080100Y)\n\n",
    "I edited the pluginconfig.xml to activate logging for the MySQL agent, and set the value of SYS_TEMP_DIR in the serviceconfig.xml to \"C:\\temp\" before starting the AC and then trying to start a MySQL agent.\n\nThe agent terminated itself very quickly after pressing \u0027Start Monitoring\u0027 in the Profile Monitor view, but no MySQL.log file was generated.\n\n",
    "I was able to successfully launch and monitor the MySQL agent when MySQL was installed on my client Windows machine.\n\nFrom the Agent Controller log that is attached, it appears as if the agent cannot connect to the remote MySQL database.  Are you sure the database is configured so it can be connected from remote systems and that all of the agent settings (db name, user, password) in the launch configuration are correct?  Are there any firewall issues that would prevent connections to the MySQL system?\n\nHere is the exception that the agent received when trying to connect:\n\nCommunications link failure due to underlying exception: \u0026#xA;\u0026#xA;** BEGIN NESTED EXCEPTION ** \u0026#xA;\u0026#xA;java.net.ConnectException\u0026#xA;MESSAGE: Connection refused: connect\u0026#xA;\u0026#xA;STACKTRACE:\u0026#xA;\u0026#xA;java.net.ConnectException: Connection refused: connect\u0026#xD;\u0026#xA;\u0026#x9;at java.net.PlainSocketImpl.socketConnect(Native Method)\u0026#xD;\u0026#xA;\u0026#x9;at java.net.PlainSocketImpl.doConnect(Unknown Source)\u0026#xD;\u0026#xA;\u0026#x9;at java.net.PlainSocketImpl.connectToAddress(Unknown Source)\u0026#xD;\u0026#xA;\u0026#x9;at java.net.PlainSocketImpl.connect(Unknown Source)\u0026#xD;\u0026#xA;\u0026#x9;at java.net.SocksSocketImpl.connect(Unknown Source)\u0026#xD;\u0026#xA;\u0026#x9;at java.net.Socket.connect(Unknown Source)\u0026#xD;\u0026#xA;\u0026#x9;at java.net.Socket.connect(Unknown Source)\u0026#xD;\u0026#xA;\u0026#x9;at java.net.Socket.\u0026lt;init\u0026gt;(Unknown Source)\u0026#xD;\u0026#xA;\u0026#x9;at java.net.Socket.\u0026lt;init\u0026gt;(Unknown Source)\u0026#xD;\u0026#xA;\u0026#x9;at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:173)\u0026#xD;\u0026#xA;\u0026#x9;at com.mysql.jdbc.MysqlIO.\u0026lt;init\u0026gt;(MysqlIO.java:268)\u0026#xD;\u0026#xA;\u0026#x9;at com.mysql.jdbc.Connection.createNewIO(Connection.java:2745)\u0026#xD;\u0026#xA;\u0026#x9;at com.mysql.jdbc.Connection.\u0026lt;init\u0026gt;(Connection.java:1553)\u0026#xD;\u0026#xA;\u0026#x9;at com.mysql",
    "Resolving this as invalid because Neil indicated the problem was a MySQL configuration problem:  \"some default setting on the server was not \nallowing remote connections\"",
    "Changed to more appropriate Product."
  ],
  "commentCreationDates": [
    "2007-05-21T17:51:13+02:00",
    "2007-05-22T16:59:23+02:00",
    "2007-05-22T19:19:40+02:00",
    "2007-05-22T19:27:17+02:00",
    "2007-05-24T21:03:15+02:00",
    "2007-05-24T21:08:41+02:00",
    "2007-05-29T00:32:04+02:00",
    "2007-06-13T07:53:27+02:00",
    "2007-09-21T19:58:28+02:00"
  ],
  "traces": [
    {
      "exceptionType": "java.net.ConnectException",
      "message": "Connection refused: connect\u0026#xD;\u0026#xA;\u0026#x9;",
      "elements": [
        {
          "method": "java.net.PlainSocketImpl.socketConnect",
          "source": "Native Method"
        }
      ],
      "number": 0,
      "commentIndex": 6,
      "bugId": "188113",
      "date": "2007-05-29T00:32:04+02:00",
      "product": "TPTP Resource Monitoring",
      "component": "Monitor.Agents",
      "severity": "critical"
    }
  ],
  "groupId": "188113",
  "bugId": "188113",
  "date": "2007-05-21T17:51:13+02:00",
  "product": "TPTP Resource Monitoring",
  "component": "Monitor.Agents",
  "severity": "critical"
}