{
  "comments": [
    "1. Start a debug session\n2. Finish the debugging session - note that Run\u003eRun to Line is disabled\n3. Click the editor and now note that Run\u003eRun to Line is enabled , click it - \nerror prompts\n\n!ENTRY org.eclipse.core.jobs 4 2 2007-06-10 13:27:52.140\n!MESSAGE An internal error occurred during: \"Run To Line\".\n!STACK 0\njava.lang.ArrayIndexOutOfBoundsException: 0\n\tat org.eclipse.php.internal.debug.core.model.PHPDebugTarget.resume(Unknown \nSource)\n\tat \norg.eclipse.debug.ui.actions.RunToLineHandler$1.run(RunToLineHandler.java:138)\n\tat org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)",
    "Unable to recreate. \nFixed a different issue that added an error to the log since the run-to-line \nbreakpoint is not added to the BreakpointManager.",
    "reopen",
    "Fixed.\nDisable the Run To Line action if the launch is not suspended.",
    "closing this bug"
  ],
  "commentCreationDates": [
    "2007-06-10T12:26:51+02:00",
    "2007-06-11T13:22:37+02:00",
    "2007-06-11T13:47:46+02:00",
    "2007-06-11T14:27:33+02:00",
    "2007-06-24T14:52:03+02:00"
  ],
  "traces": [
    {
      "exceptionType": "java.lang.ArrayIndexOutOfBoundsException",
      "message": "0",
      "elements": [
        {
          "method": "org.eclipse.php.internal.debug.core.model.PHPDebugTarget.resume",
          "source": "Unknown  Source"
        },
        {
          "method": "org.eclipse.debug.ui.actions.RunToLineHandler$1.run",
          "source": "RunToLineHandler.java:138"
        },
        {
          "method": "org.eclipse.core.internal.jobs.Worker.run",
          "source": "Worker.java:55"
        }
      ],
      "number": 0,
      "commentIndex": 0,
      "bugId": "191848",
      "date": "2007-06-10T12:26:51+02:00",
      "product": "PDT",
      "component": "Debug-core",
      "severity": "major"
    }
  ],
  "groupId": "191848",
  "bugId": "191848",
  "date": "2007-06-10T12:26:51+02:00",
  "product": "PDT",
  "component": "Debug-core",
  "severity": "major"
}