{
  "comments": [
    "Probing a subsystem with a large number of volumes (5000) causes a StackOverflowError in Derby, the probe fails:\n\n2007.08.29 11:20:18.516+02:00 ERROR org.apache.derby.client.am.SqlException: The exception \u0027java.lang.StackOverflowError\u0027 was thrown while evaluating an expression. SQLSTATE: XJ001: Java exception: \u0027: java.lang.StackOverflowError\u0027.\n\tat org.apache.derby.client.am.Statement.completeExecute(Unknown Source)\n\tat org.apache.derby.client.net.NetStatementReply.parseEXCSQLSTTreply(Unknown Source)\n\tat org.apache.derby.client.net.NetStatementReply.readExecute(Unknown Source)\n\tat org.apache.derby.client.net.StatementReply.readExecute(Unknown Source)\n\tat org.apache.derby.client.net.NetPreparedStatement.readExecute_(Unknown Source)\n\tat org.apache.derby.client.am.PreparedStatement.readExecute(Unknown Source)\n\tat org.apache.derby.client.am.PreparedStatement.flowExecute(Unknown Source)\n\tat org.apache.derby.client.am.PreparedStatement.executeUpdateX(Unknown Source)\n\tat org.apache.derby.client.am.PreparedStatement.executeUpdate(Unknown Source)\n\tat org.eclipse.aperi.infrastructure.database.DBPreparedStatement.executeUpdate(DBPreparedStatement.java:250)\n\tat org.eclipse.aperi.infrastructure.database.ComplexQuery.sqlUpdate(ComplexQuery.java:79)\n\tat org.eclipse.aperi.infrastructure.database.sql.SqlCimkeyVolume.sqlUpdate(SqlCimkeyVolume.java:48)\n\tat org.eclipse.aperi.infrastructure.history.detectability.DetectabilityService.authScanSpecialCase(DetectabilityService.java:1745)\n\tat org.eclipse.aperi.infrastructure.history.detectability.DetectabilityService.authScanUpdateDelete(DetectabilityService.java:1148)\n\tat org.eclipse.aperi.infrastructure.history.detectability.DetectabilityService.stopDiscovery(DetectabilityService.java:531)\n\tat org.eclipse.aperi.discovery.parser.GenericProcessor.end(GenericProcessor.java:482)\n\tat org.eclipse.aperi.disk.collection.DiskCIMProcessor.end(DiskCIMProcessor.java:707)\n\tat org.eclipse.aperi.disk.collection.ProbeGenericArraySubsystemProcess.process(ProbeGenericArraySubsystemProcess.java:379)\n\tat org.eclipse.aperi.Router.perform(Router.java:1050)\n\tat org.eclipse.aperi.Router.perform(Router.java:762)\n\tat org.eclipse.aperi.disk.collection.ProbeCompleteSubsystem.process(ProbeCompleteSubsystem.java:84)\n\tat org.eclipse.aperi.Router.perform(Router.java:1050)\n\tat org.eclipse.aperi.Router.perform(Router.java:762)\n\tat org.eclipse.aperi.discovery.ProcessProcessor.run(ProcessProcessor.java:57)   org.eclipse.aperi.discovery.parser.Processor end Processes (Thread-54) \n2007.08.29 11:20:52.024+02:00 ERROR org.eclipse.aperi.common.api.ServerException: HWN021503E An internal error occurred, please try again. If the problem persist, please contact IBM service.\n\tat org.eclipse.aperi.disk.common.util.DiskMessageHelper.getServerException(DiskMessageHelper.java:168)\n\n\nThe executed query also fails when executed by a external DB client:\nselect VOLUME_ID  from T_RES_CIMKEY_VOLUME where VOLUME_ID in (select T1.VOLUME_ID from T_RES_CIMKEY_VOLUME T1, T_RES_STORAGE_VOLUME T2 where T2.SVID \u003d T1.VOLUME_ID and T2.SUBSYSTEM_ID \u003d 22305) and UPDATE_TIMESTAMP \u003c \u00272007-08-29 11:38:49.935\u0027\n\nThis seems to be a known problem with our Derby version:\n\u003chttp://mail-archives.apache.org/mod_mbox/db-derby-user/200611.mbox/%3C01b701c7046a$0ca80190$8700a8c0@referentia.com%3E\u003e",
    "Using the latest Derby Version 10.1.3.4 fixes the problem.\n\nI did some smoke/regression testing in the following area and encountered\nno problems:\n\nAperi Db installation\nCIMOM/Out-of-Band discovery\nCIMOM/Out-of-Band/Data-agent probe\nseveral reports and topology viewer screens.\nStorage device deletion\n\n\nSo I would recommend to move to this Derby version within the Aperi 0.4\nrelease.\n\nTo workaround the issue before the new Derby version is checked in to Aperi CVS the new Derby version can be used by just replacing the jar\nfiles in the \\plugins\\org.eclipse.aperi.db_1.0.0 folder with the newer\nversions.\nderby.jar\nderbyclient.jar\nderbynet.jar\nderbytools.jar",
    "Tracking this via IPzilla 1830, https://dev.eclipse.org/ipzilla/show_bug.cgi?id\u003d1830",
    "Aperi-incubation-R04-071029-141055.zip"
  ],
  "commentCreationDates": [
    "2007-08-29T16:11:21+02:00",
    "2007-09-18T08:53:58+02:00",
    "2007-10-23T20:50:35+02:00",
    "2007-10-29T23:47:16+01:00"
  ],
  "traces": [
    {
      "exceptionType": "org.apache.derby.client.am.SqlException",
      "message": "The exception \u0027java.lang.StackOverflowError\u0027 was thrown while evaluating an expression. SQLSTATE: XJ001: Java exception: \u0027: java.lang.StackOverflowError\u0027.",
      "elements": [
        {
          "method": "org.apache.derby.client.am.Statement.completeExecute",
          "source": "Unknown Source"
        },
        {
          "method": "org.apache.derby.client.net.NetStatementReply.parseEXCSQLSTTreply",
          "source": "Unknown Source"
        },
        {
          "method": "org.apache.derby.client.net.NetStatementReply.readExecute",
          "source": "Unknown Source"
        },
        {
          "method": "org.apache.derby.client.net.StatementReply.readExecute",
          "source": "Unknown Source"
        },
        {
          "method": "org.apache.derby.client.net.NetPreparedStatement.readExecute_",
          "source": "Unknown Source"
        },
        {
          "method": "org.apache.derby.client.am.PreparedStatement.readExecute",
          "source": "Unknown Source"
        },
        {
          "method": "org.apache.derby.client.am.PreparedStatement.flowExecute",
          "source": "Unknown Source"
        },
        {
          "method": "org.apache.derby.client.am.PreparedStatement.executeUpdateX",
          "source": "Unknown Source"
        },
        {
          "method": "org.apache.derby.client.am.PreparedStatement.executeUpdate",
          "source": "Unknown Source"
        },
        {
          "method": "org.eclipse.aperi.infrastructure.database.DBPreparedStatement.executeUpdate",
          "source": "DBPreparedStatement.java:250"
        },
        {
          "method": "org.eclipse.aperi.infrastructure.database.ComplexQuery.sqlUpdate",
          "source": "ComplexQuery.java:79"
        },
        {
          "method": "org.eclipse.aperi.infrastructure.database.sql.SqlCimkeyVolume.sqlUpdate",
          "source": "SqlCimkeyVolume.java:48"
        },
        {
          "method": "org.eclipse.aperi.infrastructure.history.detectability.DetectabilityService.authScanSpecialCase",
          "source": "DetectabilityService.java:1745"
        },
        {
          "method": "org.eclipse.aperi.infrastructure.history.detectability.DetectabilityService.authScanUpdateDelete",
          "source": "DetectabilityService.java:1148"
        },
        {
          "method": "org.eclipse.aperi.infrastructure.history.detectability.DetectabilityService.stopDiscovery",
          "source": "DetectabilityService.java:531"
        },
        {
          "method": "org.eclipse.aperi.discovery.parser.GenericProcessor.end",
          "source": "GenericProcessor.java:482"
        },
        {
          "method": "org.eclipse.aperi.disk.collection.DiskCIMProcessor.end",
          "source": "DiskCIMProcessor.java:707"
        },
        {
          "method": "org.eclipse.aperi.disk.collection.ProbeGenericArraySubsystemProcess.process",
          "source": "ProbeGenericArraySubsystemProcess.java:379"
        },
        {
          "method": "org.eclipse.aperi.Router.perform",
          "source": "Router.java:1050"
        },
        {
          "method": "org.eclipse.aperi.Router.perform",
          "source": "Router.java:762"
        },
        {
          "method": "org.eclipse.aperi.disk.collection.ProbeCompleteSubsystem.process",
          "source": "ProbeCompleteSubsystem.java:84"
        },
        {
          "method": "org.eclipse.aperi.Router.perform",
          "source": "Router.java:1050"
        },
        {
          "method": "org.eclipse.aperi.Router.perform",
          "source": "Router.java:762"
        },
        {
          "method": "org.eclipse.aperi.discovery.ProcessProcessor.run",
          "source": "ProcessProcessor.java:57"
        }
      ],
      "number": 0,
      "commentIndex": 0,
      "bugId": "201569",
      "date": "2007-08-29T16:11:21+02:00",
      "product": "Aperi",
      "component": "aperi.db",
      "severity": "normal"
    },
    {
      "exceptionType": "org.eclipse.aperi.common.api.ServerException",
      "message": "HWN021503E An internal error occurred, please try again. If the problem persist, please contact IBM service.",
      "elements": [
        {
          "method": "org.eclipse.aperi.disk.common.util.DiskMessageHelper.getServerException",
          "source": "DiskMessageHelper.java:168"
        }
      ],
      "number": 1,
      "commentIndex": 0,
      "bugId": "201569",
      "date": "2007-08-29T16:11:21+02:00",
      "product": "Aperi",
      "component": "aperi.db",
      "severity": "normal"
    }
  ],
  "groupId": "201569",
  "bugId": "201569",
  "date": "2007-08-29T16:11:21+02:00",
  "product": "Aperi",
  "component": "aperi.db",
  "severity": "normal"
}