{
  "comments": [
    "Build ID: M20071023-1652\n\nSteps To Reproduce:\nUse the following test class:\n\nimport junit.framework.Assert;\n\nimport org.junit.Test;\n\npublic class DummyTest\n{\n\t  @Test\n\t  public void passingTest() throws Exception {\n\t    Assert.assertEquals( \"expected\", \"expected\" );\n\t  }\n\n\t  @Test\n\t  public void failingTest() throws Exception {\n\t    Assert.assertEquals( \"expected\", \"actual\" );\n\t  }\n}\n\nRun As-\u003eJunit test and you get the following stack trace (in the console - not in the JUnit view):\n\njava.lang.NoSuchMethodError: junit.framework.ComparisonFailure.getExpected()Ljava/lang/String;\n\tat org.eclipse.jdt.internal.junit4.runner.JUnit4TestListener.testFailure(JUnit4TestListener.java:62)\n\tat org.junit.runner.notification.RunNotifier$4.notifyListener(RunNotifier.java:96)\n\tat org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:37)\n\tat org.junit.runner.notification.RunNotifier.fireTestFailure(RunNotifier.java:93)\n\tat org.junit.internal.runners.MethodRoadie.addFailure(MethodRoadie.java:147)\n\tat org.junit.internal.runners.MethodRoadie.runTestMethod(MethodRoadie.java:106)\n\tat org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:79)\n\tat org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:87)\n\tat org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:77)\n\tat org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:42)\n\tat org.junit.internal.runners.JUnit4ClassRunner.invokeTestMethod(JUnit4ClassRunner.java:88)\n\tat org.junit.internal.runners.JUnit4ClassRunner.runMethods(JUnit4ClassRunner.java:51)\n\tat org.junit.internal.runners.JUnit4ClassRunner$1.run(JUnit4ClassRunner.java:44)\n\tat org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:27)\n\tat org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:37)\n\tat org.junit.internal.runners.JUnit4ClassRunner.run(JUnit4ClassRunner.java:42)\n\tat org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:38)\n\tat org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)\n\tat org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)\n\tat org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)\n\tat org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)\n\tat org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)\n\n\n\n\n\nMore information:\nLooking at the code, I can see that there are calls to getExpected() and getActual() that aren\u0027t in the API for ComparisonFailure.\n\nI\u0027m using Eclipse 3.3.1.1.",
    "Using Eclipse 3.3.1 and importing org.junit. version 4.3.1 in my workspace, I can see the getExpected() and getActual() methods on junit.framework.ComparisonFailure, so I guess the JUnit version you used or you put in your project\u0027s buildpath is not valid.\n\nWith this configuration, your example works perfectly; I can run the test either as a JUnit or JUnit Plug-in test in a Java project or Plug-in project and got the expected failure on the second test...\n",
    "Verified for 3.4M4"
  ],
  "commentCreationDates": [
    "2007-11-21T04:40:59+01:00",
    "2007-11-21T08:01:58+01:00",
    "2007-12-11T12:34:11+01:00"
  ],
  "traces": [
    {
      "exceptionType": "java.lang.NoSuchMethodError",
      "message": "junit.framework.ComparisonFailure.getExpected()Ljava/lang/String;",
      "elements": [
        {
          "method": "org.eclipse.jdt.internal.junit4.runner.JUnit4TestListener.testFailure",
          "source": "JUnit4TestListener.java:62"
        },
        {
          "method": "org.junit.runner.notification.RunNotifier$4.notifyListener",
          "source": "RunNotifier.java:96"
        },
        {
          "method": "org.junit.runner.notification.RunNotifier$SafeNotifier.run",
          "source": "RunNotifier.java:37"
        },
        {
          "method": "org.junit.runner.notification.RunNotifier.fireTestFailure",
          "source": "RunNotifier.java:93"
        },
        {
          "method": "org.junit.internal.runners.MethodRoadie.addFailure",
          "source": "MethodRoadie.java:147"
        },
        {
          "method": "org.junit.internal.runners.MethodRoadie.runTestMethod",
          "source": "MethodRoadie.java:106"
        },
        {
          "method": "org.junit.internal.runners.MethodRoadie$2.run",
          "source": "MethodRoadie.java:79"
        },
        {
          "method": "org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters",
          "source": "MethodRoadie.java:87"
        },
        {
          "method": "org.junit.internal.runners.MethodRoadie.runTest",
          "source": "MethodRoadie.java:77"
        },
        {
          "method": "org.junit.internal.runners.MethodRoadie.run",
          "source": "MethodRoadie.java:42"
        },
        {
          "method": "org.junit.internal.runners.JUnit4ClassRunner.invokeTestMethod",
          "source": "JUnit4ClassRunner.java:88"
        },
        {
          "method": "org.junit.internal.runners.JUnit4ClassRunner.runMethods",
          "source": "JUnit4ClassRunner.java:51"
        },
        {
          "method": "org.junit.internal.runners.JUnit4ClassRunner$1.run",
          "source": "JUnit4ClassRunner.java:44"
        },
        {
          "method": "org.junit.internal.runners.ClassRoadie.runUnprotected",
          "source": "ClassRoadie.java:27"
        },
        {
          "method": "org.junit.internal.runners.ClassRoadie.runProtected",
          "source": "ClassRoadie.java:37"
        },
        {
          "method": "org.junit.internal.runners.JUnit4ClassRunner.run",
          "source": "JUnit4ClassRunner.java:42"
        },
        {
          "method": "org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run",
          "source": "JUnit4TestReference.java:38"
        },
        {
          "method": "org.eclipse.jdt.internal.junit.runner.TestExecution.run",
          "source": "TestExecution.java:38"
        },
        {
          "method": "org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests",
          "source": "RemoteTestRunner.java:460"
        },
        {
          "method": "org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests",
          "source": "RemoteTestRunner.java:673"
        },
        {
          "method": "org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run",
          "source": "RemoteTestRunner.java:386"
        },
        {
          "method": "org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main",
          "source": "RemoteTestRunner.java:196"
        }
      ],
      "number": 0,
      "commentIndex": 0,
      "bugId": "210486",
      "date": "2007-11-21T04:40:59+01:00",
      "product": "JDT",
      "component": "Core",
      "severity": "normal"
    }
  ],
  "groupId": "210486",
  "bugId": "210486",
  "date": "2007-11-21T04:40:59+01:00",
  "product": "JDT",
  "component": "Core",
  "severity": "normal"
}