{
  "comments": [
    "I am using 3.0M7 and have problem with JUnit testing from within Eclipse\nresulting in a java.net.ConnectException (see below). The port number changes \nfrom time to time.\n\nI\u0027ve used it with prior version of Eclipse and my team members are runnin\nthe \"same\" setup without any problem.\nI clicked \"Run -\u003e Run as -\u003e JUnit Test\" (i.e. followed the instructions on \nhttp://www.onjava.com/lpt/a/4524)\n\nIt takes some time for the error message below to show (guess it has to timeout \nfirst).\n\nCould not connect to:  : 33131\njava.net.ConnectException: Connection refused\nat java.net.PlainSocketImpl.socketConnect(Native Method)\nat java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:305)\nat java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:171)\nat java.net.PlainSocketImpl.connect(PlainSocketImpl.java:158)\nat java.net.Socket.connect(Socket.java:452)\nat java.net.Socket.connect(Socket.java:402)\nat java.net.Socket.\u003cinit\u003e(Socket.java:309)\nat java.net.Socket.\u003cinit\u003e(Socket.java:124)\nat\norg.eclipse.jdt.internal.junit.runner.RemoteTestRunner.connect(RemoteTestRun\nner.java:640)\nat\norg.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.\njava:289)\nat\norg.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner\n.java:182)",
    "Using Mandrake 10.0 (KDE 3.2) w/ kernel 2.6.3.",
    "Moce to JDT/UI.",
    "questions:\n* can you debug a Java application?\n* do you have a firewall enabled? If yes can you disable it and try again.",
    "1. I can debug Java applications (quite advanced with RMI etc) without any \nproblems. \n\n2. No firewall is active or even installed for that matter.\n\nJust to give you some additional information. I am using three plugins:\n\n- Perforce plugin (p4eclipse.sf.net)\n- RMI plugin (genady.net)\n- MyEclipse IDE 3.7 (myeclipseide.com)\n\nMy co-workers use the same (we actually rsync our development environment just \nto make sure that it is identical) and they don\u0027t have this problem.\n",
    "I am running 3.0M8 on WinXP, having the same problem and in\nnews:eclipse.platform Steffen Hook reported this too. :-(\n\n\nSome more evidence from me:\nIn a certain workspace in an old project \"OldProj\" the unittests don\u0027t run, with\nexactly the same symptoms as Jimisola described above, no matter how I try to\nstart them.\n\nIf I create a new project \"NewProj\" in this workspace with a JUnit test in it, I\ncan run the test (e.g. via context menu Run-\u003eRun JUnit Test), and everything\nworks as it should: The test runs, results are gathered ...\n\nNow I copy this new test from \"NewProj\" into the old project \"OldProj\" and try\nto run it there: Again it does _not_ run, with the same symptoms (Connection\nrefused).\n\n\n\nI also observed another failing behaviour, unsure whether there is a correlation:\nI can simply make a copy of \"NewProj\" in the PackageExplorer via the copy and\npaste keys (Ctrl-C, Ctrl-V).\nIf I try to do this with \"OldProj\", I get \"The command for the key you pressed\nfailed\" on paste (Ctrl-V) with the following log entry (truncated). This seems\nto be something totally different but that both problems happen on the same\nprojects may indicate something.\n\njava.lang.NullPointerException\nat\norg.eclipse.jdt.internal.corext.refactoring.reorg.ReorgUtils.getResource(ReorgUtils.java:116)\nat\norg.eclipse.jdt.internal.corext.refactoring.reorg.ReorgUtils.getResources(ReorgUtils.java:122)\nat\norg.eclipse.jdt.internal.ui.refactoring.reorg.PasteAction$ProjectPaster.getProjectsToPaste(PasteAction.java:285)\nat\norg.eclipse.jdt.internal.ui.refactoring.reorg.PasteAction$ProjectPaster.pasteProjects(PasteAction.java:269)\nat\norg.eclipse.jdt.internal.ui.refactoring.reorg.PasteAction$ProjectPaster.paste(PasteAction.java:265)\nat\norg.eclipse.jdt.internal.ui.refactoring.reorg.PasteAction.run(PasteAction.java:191)\nat\norg.eclipse.jdt.ui.actions.SelectionDispatchAction.dispatchRun(SelectionDispatchAction.java:212)\n\n\nJimisola: Is this the same for you?",
    "Marko - how do the build class paths between the old and the new projects \ndiffer? Do both projects refer the same junit.jar?",
    "Both are plugin projects (sorry, forgot to mention that). \n\nJunit is a project in the workspace which they both require in their plugin.xml\nand after \"Update Buildpath\" JUnit shows up in Properties-\u003eJava Build\nPath-\u003eLibraries-\u003ePlug-in Dependencies-\u003eorg.junit .\n\n\nThe OldProj also has other plug-in requirements. Removing them results in some\ncompiler error (of course) in other classes, but the mentioned test class still\ncannot be run (after the warning about the compiler errors)",
    "OK, I found the crucial difference between the two projects: The project, in\nwhich the error occurs, contains a tilde (~) in its project name. This also\ncauses the refactoring problem I described as a sidenote (which is handled in\nbug 47815).\n\nAs soon as I remove all tildes from the project name JUnit works again.\n\n\n\nJimisola, do you also have special characters in your project name?",
    "This means the VM running the tests cannot be launched because of the special \ncharacters. Can you please paste in the resulting command line:\n1) run the JUnit test\n2) switch to the debug view\n3) select the child (process node) of the JUnit node\n4) properties\n-\u003e the command line shows up in the properties dialog",
    "The command line is the same (besides the always changing port number), whether\nJUnit starts successfully or not.\n\n\nAfter further investigation and debugging a run-time workbench, in which I\nstartet the tests, it seems to me, that the problem with the special characters\nreally is the same as in bug 47815:\n\nI tracked the problem to JUnitPlugin.java, line 248: \n    IJavaElement element\u003d JavaCore.create(typeStr);\n\nHere JavaCore.create() returns a null, propable because of the tilde in typeStr.\nSo my problem really seems to lie in the domain of JavaCore.",
    "this may be related to Bug 58633. I have a project wich has a parenthasis in \nits name and I am getting the same symptoms. I think this bug is a major one as \nis Bug 58633.",
    "Good work Marko! Sorry for the delay in my reply (have been out of office).\n\nHowever, I can only confirm what you already know for sure now.\nThe problem was caused due to my project name which was on the form \"ProjectName\n(branch)\".\n\nI have checked out the two other bugs and I am familiar with them as well ;)\n\nHope that the Eclipse team changes the severity of this one to major as well and\ntarget it for M9.",
    "verified that the problem is the same as in bug# 47815. The parenthesis is a \nseparator used by the handle format.\n\n\n\n*** This bug has been marked as a duplicate of 47815 ***"
  ],
  "commentCreationDates": [
    "2004-03-21T18:47:14+01:00",
    "2004-03-21T18:48:53+01:00",
    "2004-03-22T02:36:57+01:00",
    "2004-03-23T14:02:12+01:00",
    "2004-03-23T20:53:20+01:00",
    "2004-04-14T14:32:30+02:00",
    "2004-04-14T14:42:19+02:00",
    "2004-04-14T15:08:51+02:00",
    "2004-04-16T08:00:06+02:00",
    "2004-04-16T10:13:34+02:00",
    "2004-04-16T11:46:17+02:00",
    "2004-04-16T11:49:01+02:00",
    "2004-04-16T14:10:34+02:00",
    "2004-04-16T14:47:18+02:00"
  ],
  "traces": [
    {
      "exceptionType": "java.net.ConnectException",
      "message": "Connection refused",
      "elements": [
        {
          "method": "java.net.PlainSocketImpl.socketConnect",
          "source": "Native Method"
        },
        {
          "method": "java.net.PlainSocketImpl.doConnect",
          "source": "PlainSocketImpl.java:305"
        },
        {
          "method": "java.net.PlainSocketImpl.connectToAddress",
          "source": "PlainSocketImpl.java:171"
        },
        {
          "method": "java.net.PlainSocketImpl.connect",
          "source": "PlainSocketImpl.java:158"
        },
        {
          "method": "java.net.Socket.connect",
          "source": "Socket.java:452"
        },
        {
          "method": "java.net.Socket.connect",
          "source": "Socket.java:402"
        },
        {
          "method": "java.net.Socket.\u003cinit\u003e",
          "source": "Socket.java:309"
        },
        {
          "method": "java.net.Socket.\u003cinit\u003e",
          "source": "Socket.java:124"
        },
        {
          "method": "org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.connect",
          "source": "RemoteTestRun ner.java:640"
        },
        {
          "method": "org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run",
          "source": "RemoteTestRunner. java:289"
        },
        {
          "method": "org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main",
          "source": "RemoteTestRunner .java:182"
        }
      ],
      "number": 0,
      "commentIndex": 0,
      "bugId": "55480",
      "duplicateId": "47815",
      "date": "2004-03-21T18:47:14+01:00",
      "product": "JDT",
      "component": "UI",
      "severity": "normal"
    },
    {
      "exceptionType": "java.lang.NullPointerException",
      "elements": [
        {
          "method": "org.eclipse.jdt.internal.corext.refactoring.reorg.ReorgUtils.getResource",
          "source": "ReorgUtils.java:116"
        },
        {
          "method": "org.eclipse.jdt.internal.corext.refactoring.reorg.ReorgUtils.getResources",
          "source": "ReorgUtils.java:122"
        },
        {
          "method": "org.eclipse.jdt.internal.ui.refactoring.reorg.PasteAction$ProjectPaster.getProjectsToPaste",
          "source": "PasteAction.java:285"
        },
        {
          "method": "org.eclipse.jdt.internal.ui.refactoring.reorg.PasteAction$ProjectPaster.pasteProjects",
          "source": "PasteAction.java:269"
        },
        {
          "method": "org.eclipse.jdt.internal.ui.refactoring.reorg.PasteAction$ProjectPaster.paste",
          "source": "PasteAction.java:265"
        },
        {
          "method": "org.eclipse.jdt.internal.ui.refactoring.reorg.PasteAction.run",
          "source": "PasteAction.java:191"
        },
        {
          "method": "org.eclipse.jdt.ui.actions.SelectionDispatchAction.dispatchRun",
          "source": "SelectionDispatchAction.java:212"
        }
      ],
      "number": 1,
      "commentIndex": 5,
      "bugId": "55480",
      "duplicateId": "47815",
      "date": "2004-04-14T14:32:30+02:00",
      "product": "JDT",
      "component": "UI",
      "severity": "normal"
    }
  ],
  "groupId": "47815",
  "bugId": "55480",
  "duplicateId": "47815",
  "date": "2004-03-21T18:47:14+01:00",
  "product": "JDT",
  "component": "UI",
  "severity": "normal"
}