{
  "comments": [
    "Deploying to an invalid location (a root directory defined in a location that \nis invalid) causes the following exception.  I have verified that the same \nproblem exists from Windows to Windows and from Windows deploying to Linux.  \nTo reproduce the problem set a root directory on a location that is invalid \nfor the deployment platform, for example, for a Windows deployment location \nset \"/some/linux/directory\" as the root directory.  This should cause the \nstack trace like below.  The recommendation would be to create a more \ninformative error message that instructs the user of the \"real\" underlying \nproblem (malformed directory names) or do early-checking and try to validate \nthe root directory before-hand (if possible).  \n\njava.lang.RuntimeException: java.net.SocketException: Software caused \nconnection abort: socket write error\n\tat \norg.eclipse.hyades.execution.local.file.FileManagerImpl$ResourceConnection$Sock\netReader.run(FileManagerImpl.java:301)\n\tat \norg.eclipse.hyades.execution.local.file.FileManagerImpl$ResourceConnection.init\n(FileManagerImpl.java:201)\n\tat \norg.eclipse.hyades.internal.execution.local.control.ConnectionImpl.connect\n(ConnectionImpl.java:90)\n\tat org.eclipse.hyades.execution.local.file.FileManagerImpl.putFile\n(FileManagerImpl.java:163)\n\tat \norg.eclipse.hyades.execution.harness.JavaExecutionDeploymentAdapter.deployFile\n(JavaExecutionDeploymentAdapter.java:381)\n\tat \norg.eclipse.hyades.execution.harness.JavaExecutionDeploymentAdapter.deployToNod\ne(JavaExecutionDeploymentAdapter.java:364)\n\tat \norg.eclipse.hyades.execution.harness.JavaExecutionDeploymentAdapter.deployTestA\nssets(JavaExecutionDeploymentAdapter.java:91)\n\tat \norg.eclipse.hyades.execution.harness.util.ExecutionAdapterUtilities.adaptExecut\nionDeployment(ExecutionAdapterUtilities.java:134)\n\tat org.eclipse.hyades.execution.harness.TestExecutionHarness.launchTest\n(TestExecutionHarness.java:1306)\n\tat org.eclipse.hyades.execution.harness.TestExecutionHarness.launchTest\n(TestExecutionHarness.java:562)\n\tat \norg.eclipse.hyades.test.ui.launch.delegates.BasicTestLaunchConfigurationDelegat\ne2.invokeTestExecutionHarness(BasicTestLaunchConfigurationDelegate2.java:140)\n\tat \norg.eclipse.hyades.test.ui.launch.delegates.AbstractLaunchConfigurationDelegate\n2.launch(AbstractLaunchConfigurationDelegate2.java:164)\n\tat org.eclipse.debug.internal.core.LaunchConfiguration.launch\n(LaunchConfiguration.java:569)\n\tat org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch\n(DebugUIPlugin.java:788)\n\tat org.eclipse.debug.internal.ui.DebugUIPlugin$6.run\n(DebugUIPlugin.java:955)\n\tat org.eclipse.core.internal.jobs.Worker.run(Worker.java:66)\nCaused by: java.net.SocketException: Software caused connection abort: socket \nwrite error\n\tat java.net.SocketOutputStream.socketWrite0(Native Method)\n\tat java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)\n\tat java.net.SocketOutputStream.write(SocketOutputStream.java:157)\n\tat \norg.eclipse.hyades.execution.local.file.FileManagerImpl$ResourceConnection$Sock\netReader.run(FileManagerImpl.java:290)\n\t... 15 more",
    "Now that we have a \"3.3\" Version in bugzilla, updating bugzillas targeted to 3.3\nor a 3.3 iteration so that their Version matches their Target. \"future\",\n\"unspecified\", \"4.0\", and \"4.1\" Versions will not be updated.",
    "Now, deploying to an invalid location (a root directory defined in a location that \nis invalid), will cause the following more descriptive message to occur:\n\nIWAT4039E The Test Execution Harness reported the following\nproblems:org.eclipse.core.runtime.CoreException\n  IWAT4039E The Test Execution Harness reported the following problems:Atempting\nto deploy file to x:/foo/bar/NewJavaProject/TestFolder/jUnitTest.class caused\nexception :java.io.IOException\n"
  ],
  "commentCreationDates": [
    "2004-11-24T21:15:04+01:00",
    "2005-03-15T23:17:05+01:00",
    "2005-04-05T22:02:33+02:00"
  ],
  "traces": [
    {
      "exceptionType": "java.net.SocketException",
      "message": "Software caused  connection abort: socket write error",
      "elements": [
        {
          "method": "org.eclipse.hyades.execution.local.file.FileManagerImpl$ResourceConnection$SocketReader.run",
          "source": "FileManagerImpl.java:301"
        },
        {
          "method": "org.eclipse.hyades.execution.local.file.FileManagerImpl$ResourceConnection.init",
          "source": "FileManagerImpl.java:201"
        },
        {
          "method": "org.eclipse.hyades.internal.execution.local.control.ConnectionImpl.connect",
          "source": "ConnectionImpl.java:90"
        },
        {
          "method": "org.eclipse.hyades.execution.local.file.FileManagerImpl.putFile",
          "source": "FileManagerImpl.java:163"
        },
        {
          "method": "org.eclipse.hyades.execution.harness.JavaExecutionDeploymentAdapter.deployFile",
          "source": "JavaExecutionDeploymentAdapter.java:381"
        },
        {
          "method": "org.eclipse.hyades.execution.harness.JavaExecutionDeploymentAdapter.deployToNode",
          "source": "JavaExecutionDeploymentAdapter.java:364"
        },
        {
          "method": "org.eclipse.hyades.execution.harness.JavaExecutionDeploymentAdapter.deployTestAssets",
          "source": "JavaExecutionDeploymentAdapter.java:91"
        },
        {
          "method": "org.eclipse.hyades.execution.harness.util.ExecutionAdapterUtilities.adaptExecutionDeployment",
          "source": "ExecutionAdapterUtilities.java:134"
        },
        {
          "method": "org.eclipse.hyades.execution.harness.TestExecutionHarness.launchTest",
          "source": "TestExecutionHarness.java:1306"
        },
        {
          "method": "org.eclipse.hyades.execution.harness.TestExecutionHarness.launchTest",
          "source": "TestExecutionHarness.java:562"
        },
        {
          "method": "org.eclipse.hyades.test.ui.launch.delegates.BasicTestLaunchConfigurationDelegate2.invokeTestExecutionHarness",
          "source": "BasicTestLaunchConfigurationDelegate2.java:140"
        },
        {
          "method": "org.eclipse.hyades.test.ui.launch.delegates.AbstractLaunchConfigurationDelegate2.launch",
          "source": "AbstractLaunchConfigurationDelegate2.java:164"
        },
        {
          "method": "org.eclipse.debug.internal.core.LaunchConfiguration.launch",
          "source": "LaunchConfiguration.java:569"
        },
        {
          "method": "org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch",
          "source": "DebugUIPlugin.java:788"
        },
        {
          "method": "org.eclipse.debug.internal.ui.DebugUIPlugin$6.run",
          "source": "DebugUIPlugin.java:955"
        },
        {
          "method": "org.eclipse.core.internal.jobs.Worker.run",
          "source": "Worker.java:66"
        }
      ],
      "causedBy": {
        "exceptionType": "java.net.SocketException",
        "message": "Software caused connection abort: socket  write error",
        "elements": [
          {
            "method": "java.net.SocketOutputStream.socketWrite0",
            "source": "Native Method"
          },
          {
            "method": "java.net.SocketOutputStream.socketWrite",
            "source": "SocketOutputStream.java:113"
          },
          {
            "method": "java.net.SocketOutputStream.write",
            "source": "SocketOutputStream.java:157"
          },
          {
            "method": "org.eclipse.hyades.execution.local.file.FileManagerImpl$ResourceConnection$SocketReader.run",
            "source": "FileManagerImpl.java:290"
          }
        ],
        "number": 0,
        "commentIndex": 0
      },
      "number": 0,
      "commentIndex": 0,
      "bugId": "79446",
      "date": "2004-11-24T21:15:04+01:00",
      "product": "Hyades",
      "component": "Exec.harness",
      "severity": "normal"
    }
  ],
  "groupId": "79446",
  "bugId": "79446",
  "date": "2004-11-24T21:15:04+01:00",
  "product": "Hyades",
  "component": "Exec.harness",
  "severity": "normal"
}