{
  "comments": [
    "This is with Eclipse 3.1M5a and AJDT 20050225125806.\n\n// Test.java\npublic class Test {\n\tpublic static void main(String[] args) {\n\t\t\n\t}\n}\n\nIMPORTANT: Aspect must use .java extension to reproduce the bug\n// TestAspect.java \npublic aspect TestAspect {\n\tbefore() : execution(* Test.main(..)) {\n\t\tthrow new RuntimeException();\n\t}\n}\n\n- Execute and you will get the following stack trace:\njava.lang.RuntimeException\n\tat TestAspect.ajc$before$TestAspect$1$726c2979(TestAspect.java:9)\n\tat Test.main(Test.java)\nException in thread \"main\" \n\n- Click on \"TestAspect.ajc$before$TestAspect$1$726c2979(TestAspect.java:9)\"\n\nBug:\nA dialog pops up saying:\n\"Sources not found for TestAspect.ajc\"",
    "I have been unable to reproduce the bug in either Eclipse 3.0 or Eclipse 3.1\nwith their latest respective builds of AJDT.  For this reason, I believe that\nthe problem has been fixed post-M5a, or in a more recent build of AJDT, and\ntherefore will mark the bug as fixed. If you are able to reproduce the bug\nagain, please reopen it."
  ],
  "commentCreationDates": [
    "2005-03-01T16:28:08+01:00",
    "2005-08-09T11:35:30+02:00"
  ],
  "traces": [
    {
      "exceptionType": "java.lang.RuntimeException",
      "elements": [
        {
          "method": "TestAspect.ajc$before$TestAspect$1$726c2979",
          "source": "TestAspect.java:9"
        },
        {
          "method": "Test.main",
          "source": "Test.java"
        }
      ],
      "number": 0,
      "commentIndex": 0,
      "bugId": "86913",
      "date": "2005-03-01T16:28:08+01:00",
      "product": "AJDT",
      "component": "UI",
      "severity": "normal"
    }
  ],
  "groupId": "86913",
  "bugId": "86913",
  "date": "2005-03-01T16:28:08+01:00",
  "product": "AJDT",
  "component": "UI",
  "severity": "normal"
}