{
  "comments": [
    "If I place a break point in a inner class, when debugging the debugger is not\nable to find the source code.\n\nAnd also if I click in the Inner Class link at the console, the class isn?t\nfound either.",
    "Please provide an example. What build are you using? Is this a dup of 80191 \n(which has been fixed)?",
    "Build 3.1M7\n\nHere?s a code snippet that reproduces the bug:\n\nBugTest.java\n\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\npublic class BugTest {\n\tpublic static void main( String[] args ) {\n\t\tnew InnerBugTest();\n\t}\n}\nclass InnerBugTest {\n\tpublic InnerBugTest() {\n\t\tif( true )\n\t\t\tthrow new RuntimeException( \"Should I go here?\" );\n\t}\n}\n\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\n\nWhen executed, the console shows the following:\n\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\nException in thread \"main\" java.lang.RuntimeException: Should I go here?\n\tat InnerBugTest.\u003cinit\u003e(BugTest.java:15)\n\tat BugTest.main(BugTest.java:6)\n\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\n\nAnd if I click the two links (BugTest.java:15 and BugTest.java:6), I get the\nfollowing error message:\n\u0027Source not found for BugTest\u0027.\n\nAlso tested with a package other than the default.",
    "Works for me in N20050525",
    "Well, it must be some plugin I?ve installed then.\n\nSorry and thanks."
  ],
  "commentCreationDates": [
    "2005-05-23T17:16:10+02:00",
    "2005-05-24T15:11:22+02:00",
    "2005-05-25T03:25:25+02:00",
    "2005-05-25T23:11:43+02:00",
    "2005-05-26T22:05:41+02:00"
  ],
  "traces": [
    {
      "exceptionType": "java.lang.RuntimeException",
      "message": "Should I go here?",
      "elements": [
        {
          "method": "InnerBugTest.\u003cinit\u003e",
          "source": "BugTest.java:15"
        },
        {
          "method": "BugTest.main",
          "source": "BugTest.java:6"
        }
      ],
      "number": 0,
      "commentIndex": 2,
      "bugId": "96310",
      "date": "2005-05-25T03:25:25+02:00",
      "product": "JDT",
      "component": "Debug",
      "severity": "normal"
    }
  ],
  "groupId": "96310",
  "bugId": "96310",
  "date": "2005-05-23T17:16:10+02:00",
  "product": "JDT",
  "component": "Debug",
  "severity": "normal"
}